### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by RobenV** [Tuhinshubhra/Facebook-Video-Downloader#1]
Kindly help to rectify the following error.

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/Facebook-Video-Downloader/fb.php:3
Stack trace:
#0 /root/Facebook-Video-Downloader/fb.php(28): curl('https://mbasic....')
#1 {main}
  thrown in /root/Facebook-Video-Downloader/fb.php on line 3

**Comment by Tuhinshubhra** [comment]
Check this thread out: https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

**Comment by sexxxxladies-netizen** [comment]
// Source - https://stackoverflow.com/a/6382581
// Posted by rahim asgari, modified by community. See post 'Timeline' for change history
// Retrieved 2026-08-18, License - CC BY-SA 4.0

sudo service apache2 restart
